version: '3'
services:
    mr-unred:
        build:
            context: docker/mr-unred
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: mr-unrd
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src:/var/www/html'
        networks:
            - mr-unred
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:5.7'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mr-unred-mysql:/var/lib/mysql'
        networks:
            - mr-unred
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - mr-unred
networks:
    mr-unred:
        driver: bridge
volumes:
    mr-unred-mysql:
        driver: local
